### ISSUE TITLE
instructions how to use

### ISSUE THREAD

**Issue by rdbath** [stadt-bielefeld/mapfile-lint#1]
Hi there,
are there any instructions how to proper install and use mapfile-lint?
I tried to install it but it did not work:

`D:\Programme>npm i mapfile-lint
npm WARN saveError ENOENT: no such file or directory, open 'D:\Programme\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Programme\package.json'
npm WARN Programme No description
npm WARN Programme No repository field.
npm WARN Programme No README data
npm WARN Programme No license field.

+ mapfile-lint@0.0.1
updated 1 package and audited 3 packages in 1.994s
found 0 vulnerabilities`

**Comment by geofreak** [comment]
This module has not been implemented yet.

It is an empty repository

**Comment by geofreak** [comment]
Only the parser and writer is working.

See https://github.com/stadt-bielefeld/mapfile2js
